### ISSUE TITLE
ClientID

### ISSUE THREAD

**Issue by zeadope-zz** [opdoffer/toon-homeassistant#1]
Sinds vandaag heb ik de volgende issue met toon-homeassistant.

```
python /home/homeassistant/.homeassistant/includes/scripts/toon/toonclient.py -t -p -g -c -U <USER> -P <PASS>
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/includes/scripts/toon/toonclient.py", line 26, in <module>
    toon.login()
  File "/home/homeassistant/.homeassistant/includes/scripts/toon/toon.py", line 42, in login
    formdata = {"clientId": self.sessiondata["clientId"],
KeyError: 'clientId'
```

Ik heb de afgelopen dagen niks gewijzigd. Heb HA al opnieuw gestart. De toon heeft WiFi en is verbonden met de service. De Android App deed sinds gisteren ook al raar en bleef hangen op het splash scherm.

**Comment by opdoffer** [comment]
Het lijkt erop dat dit probleem bij Eneco ligt. Maar dat is eerste inschatting. Ik hoop nog niet dat ze de webapp hebben dichtgezet en alles nu al via de api moet.

**Comment by opdoffer** [comment]
Eneco heeft problemen zo lijkt: https://forum.eneco.nl/storingen-problemen-112/storing-servicecenter-09-10-2016-update-1059-11959/index3.html#post121147

**Comment by zeadope-zz** [comment]
Dat kan ik inderdaad bevestigen. Zojuist via de iPad geprobeerd in te loggen. 

> Geen verbinding met het Service Center
> Het Service Center is momenteel niet blijkbaar. Probeer het later nog een keer.
> ... 
> 
> Excuses voor het ongemak.
